/**
 * 装机脚本。`GET /install-manager.sh` 把它按请求的 Host 填好之后原样吐出去。
 *
 * 目标是一条命令：
 *
 *   curl -fsSL https://gw/install-manager.sh | sudo bash -s -- --code SW-XXXX-XXXX
 *
 * 之后这台 Debian 上不用再敲任何东西——建席位账号、装桌面栈、起 bot、以后自己
 * 升级，全归管家。
 *
 * 脚本本身要能重复跑：换过配对码、或者管家版本升不动了，重跑一次就是修复手段。
 *
 * **脚本内容全部英文。** 它跑在别人的服务器上，那儿的 locale 可能是 `C`——中文
 * 输出会变成一屏乱码，而这恰好是装机出问题时唯一能看的东西。仓库里其余地方的
 * 注释仍然用中文：那些不会打到那台机器的终端上。
 */

/** 管家包里带 tsx，不带 Node。这是运行 `node:sqlite` 和现代语法的下限。 */
const NODE_MAJOR = 24

export function installScript(gatewayUrl: string): string {
  return `#!/bin/bash
# Satuwork machine manager installer. Generated by ${gatewayUrl}.
#
#   curl -fsSL ${gatewayUrl}/install-manager.sh | sudo bash -s -- --code SW-XXXX-XXXX
#
# Safe to re-run: it reinstalls and restarts the service. An already paired
# machine stays paired.
set -euo pipefail

GATEWAY_URL=${JSON.stringify(gatewayUrl)}
CODE=""
PORT=8443
while [ $# -gt 0 ]; do
  case "$1" in
    --code) CODE="\${2:-}"; shift 2 ;;
    --port) PORT="\${2:-8443}"; shift 2 ;;
    --gateway) GATEWAY_URL="\${2:-}"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [ "$(id -u)" != 0 ]; then echo "must run as root (prefix with sudo)" >&2; exit 1; fi
if [ -z "$CODE" ] && [ ! -f /etc/satuwork/manager.json ]; then
  echo "--code is required: generate one on the company page in the Gateway console" >&2
  exit 2
fi

echo "==> Checking Node"
NEED_NODE=1
if command -v node >/dev/null 2>&1; then
  CUR="$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)"
  if [ "$CUR" -ge ${NODE_MAJOR} ]; then NEED_NODE=0; fi
fi
if [ "$NEED_NODE" = 1 ]; then
  echo "    installing Node ${NODE_MAJOR}"
  apt-get update -y
  DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl gnupg
  curl -fsSL https://deb.nodesource.com/setup_${NODE_MAJOR}.x | bash -
  DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs
fi
# The unit hardcodes /usr/bin/node: systemd does not consult PATH, so a Node
# installed elsewhere fails with 203/EXEC.
if [ ! -x /usr/bin/node ]; then ln -sf "$(command -v node)" /usr/bin/node; fi

echo "==> Downloading the manager"
apt-get install -y curl tar >/dev/null 2>&1 || true
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
curl -fsSL "$GATEWAY_URL/manager/release?code=$CODE" -o "$TMP/manager.tgz"
STAGED=/opt/satuwork/manager/releases/staged.$$
mkdir -p "$STAGED"
tar -xzf "$TMP/manager.tgz" -C "$STAGED"
[ -f "$STAGED/bin/satuwork-manager.mjs" ] || { echo "package has no bin/satuwork-manager.mjs" >&2; exit 1; }
VERSION="$(cat "$STAGED/VERSION" 2>/dev/null || echo unknown)"
FINAL="/opt/satuwork/manager/releases/$VERSION"
rm -rf "$FINAL"
mv "$STAGED" "$FINAL"
# 'current' is what the systemd unit points at, and what self-upgrade swaps.
# Create then rename so the swap is atomic.
ln -sfn "$FINAL" /opt/satuwork/manager/.current.tmp
mv -T /opt/satuwork/manager/.current.tmp /opt/satuwork/manager/current
echo "    $VERSION"

echo "==> Writing config"
mkdir -p /etc/satuwork
cat > /etc/satuwork/manager.env << EOF_ENV
GATEWAY_URL=$GATEWAY_URL
SATUWORK_MANAGER_PORT=$PORT
SATUWORK_PAIRING_CODE=$CODE
EOF_ENV
chmod 600 /etc/satuwork/manager.env

cat > /etc/systemd/system/satuwork-manager.service << 'EOF_UNIT'
[Unit]
Description=Satuwork machine manager
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
# root: it creates Linux accounts, writes /etc/systemd, and starts seat units.
User=root
# Required: 'tsx' in --import is a bare specifier and Node resolves it from the
# working directory, not from the script's location. Without this, cwd is / and
# the service dies at startup with ERR_MODULE_NOT_FOUND. systemd resolves the
# symlink at start, so an upgrade picks up the new release.
WorkingDirectory=/opt/satuwork/manager/current
EnvironmentFile=/etc/satuwork/manager.env
ExecStart=/usr/bin/node --import tsx /opt/satuwork/manager/current/bin/satuwork-manager.mjs
Restart=always
RestartSec=3
# Must NOT be control-group: the seat units (slim-desktop@ / satuwork-bot@) are
# independent system units and must not die with the manager. Restarting the
# manager leaves every seat running.
KillMode=process
TimeoutStopSec=15

[Install]
WantedBy=multi-user.target
EOF_UNIT

# Rollback safety net for self-upgrade. The selftest only proves the new build
# starts; it cannot prove it can still reach the Gateway. That failure means an
# unreachable machine, and this architecture has no SSH left to rescue it.
cat > /etc/systemd/system/satuwork-manager-confirm.service << 'EOF_CONFIRM'
[Unit]
Description=Roll back Satuwork manager if the new version never checked in

[Service]
Type=oneshot
ExecStart=/usr/local/bin/satuwork-manager-confirm.sh
EOF_CONFIRM

cat > /etc/systemd/system/satuwork-manager-confirm.timer << 'EOF_TIMER'
[Unit]
Description=Check the Satuwork manager settled after an upgrade

[Timer]
OnBootSec=120
OnUnitActiveSec=120
AccuracySec=15

[Install]
WantedBy=timers.target
EOF_TIMER

cat > /usr/local/bin/satuwork-manager-confirm.sh << 'EOF_SCRIPT'
#!/bin/bash
# A new manager records its own version in confirmedVersion only after one
# successful heartbeat. Still unset 120s after the swap means it came up but
# cannot talk to the Gateway: point 'current' back and restart.
set -euo pipefail
ROOT=/opt/satuwork/manager
STATE=/etc/satuwork/manager.json
[ -L "$ROOT/previous" ] || exit 0
[ -f "$STATE" ] || exit 0
CUR="$(basename "$(readlink -f "$ROOT/current")")"
OK="$(node -p 'JSON.parse(require("fs").readFileSync("'"$STATE"'","utf8")).confirmedVersion||""' 2>/dev/null || echo "")"
[ "$OK" = "$CUR" ] && exit 0
# A machine that has never paired has no confirmedVersion to compare against.
# Do not mistake that for a failed upgrade.
[ -z "$OK" ] && exit 0
logger -t satuwork-manager "version $CUR started but never checked in; rolling back to $(basename "$(readlink -f "$ROOT/previous")")"
ln -sfn "$(readlink -f "$ROOT/previous")" "$ROOT/.current.tmp"
mv -T "$ROOT/.current.tmp" "$ROOT/current"
rm -f "$ROOT/previous"
systemctl restart satuwork-manager.service
EOF_SCRIPT
chmod 755 /usr/local/bin/satuwork-manager-confirm.sh

echo "==> Starting"
systemctl daemon-reload
systemctl enable --now satuwork-manager-confirm.timer >/dev/null
systemctl enable satuwork-manager.service >/dev/null
systemctl restart satuwork-manager.service

echo "==> Waiting for pairing"
for _ in $(seq 1 30); do
  if [ -f /etc/satuwork/manager.json ]; then break; fi
  sleep 1
done
if [ ! -f /etc/satuwork/manager.json ]; then
  echo "pairing did not complete. Check: journalctl -u satuwork-manager -n 50" >&2
  exit 1
fi
# The pairing code is single use; no reason to leave it on disk.
sed -i '/^SATUWORK_PAIRING_CODE=/d' /etc/satuwork/manager.env
echo
echo "Paired. Machine manager $VERSION is listening on :$PORT"
echo "Deploy bots to employees from the Gateway; this machine needs no further commands."
`
}
